variables:
- name: SolutionBaseName
  value: 'DFC.FutureAccessModel.LocalAuthorities'
- name: BuildPlatform
  value: 'any cpu'
- name: BuildConfiguration
  value: 'release'
- group: dfc-shared-all
- group: dfc-futureaccessmodel-shared-all

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.10.3
    endpoint: 'GitHub (ESFA)'

stages:
- stage: Build
  displayName: Build, Test and Analyze
  jobs:
  - job: BuildTestAndAnalyze
    pool:
      name: NCS - CI and CD
      demands:
      - msbuild
      - visualstudio
    steps:
    - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
      parameters:
        ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'
        SolutionBaseName: $(SolutionBaseName)
        PublishPipelineArtifact: true
    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-sonar.yml@dfc-devops
      parameters:
        SolutionBaseName: $(SolutionBaseName)
        BuildPlatform: 'any cpu'
        BuildConfiguration: 'release'

- stage: DeployTo_LAB
  displayName: Deploy to LAB_FUTUREACCESSMODEL environment
  condition: succeeded()
  variables:
  - group: dfc-shared-lab
  - group: dfc-futureaccessmodel-shared-lab
  - template: VariableTemplates\SharedEnvironmentVariables.yml
  - template: VariableTemplates\LabEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/Deploy.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      Environment: LAB_FUTUREACCESSMODEL
      FunctionAppName: dfc-lab-fam-la-fa
      ResourceGroup: dfc-lab-fam-la-rg
      ApimResourceGroup: '$(sharedResourceGroup)'
      ApimInstanceName: '$(ApimServiceName)'
      ApimProductId: '${{ variables.ApimProductId }}'
      ApiName: '${{ variables.ApimApiName }}'
      SwaggerSpecificationUrl: 'https://dfc-lab-fam-la-fa.$(FunctionAppDomain)${{ variables.SwaggerDefinitionPath }}'

- stage: DeployTo_DEV
  displayName: Deploy to DEV_FUTUREACCESSMODEL environment
  condition: succeeded()
  variables:
  - group: dfc-shared-dev
  - group: dfc-futureaccessmodel-shared-dev
  - template: VariableTemplates\SharedEnvironmentVariables.yml
  - template: VariableTemplates\DevEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/Deploy.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      Environment: DEV_FUTUREACCESSMODEL
      FunctionAppName: dfc-dev-fam-la-fa
      ResourceGroup: dfc-dev-fam-la-rg
      ApimResourceGroup: '$(sharedResourceGroup)'
      ApimInstanceName: '$(ApimServiceName)'
      ApimProductId: '${{ variables.ApimProductId }}'
      ApiName: '${{ variables.ApimApiName }}'
      SwaggerSpecificationUrl: 'https://dfc-dev-fam-la-fa.$(FunctionAppDomain)${{ variables.SwaggerDefinitionPath }}'

- stage: DeployTo_SIT
  displayName: Deploy to SIT_FUTUREACCESSMODEL environment
  condition: succeeded()
  variables:
  - group: dfc-shared-sit
  - group: dfc-futureaccessmodel-shared-sit
  - template: VariableTemplates\SharedEnvironmentVariables.yml
  - template: VariableTemplates\SitEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/Deploy.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      Environment: SIT_FUTUREACCESSMODEL
      FunctionAppName: dfc-sit-fam-la-fa
      ResourceGroup: dfc-sit-fam-la-rg
      ApimResourceGroup: '$(sharedResourceGroup)'
      ApimInstanceName: '$(ApimServiceName)'
      ApimProductId: '${{ variables.ApimProductId }}'
      ApiName: '${{ variables.ApimApiName }}'
      SwaggerSpecificationUrl: 'https://dfc-sit-fam-la-fa.$(FunctionAppDomain)${{ variables.SwaggerDefinitionPath }}'

- stage: DeployTo_PP
  displayName: Deploy to PP_FUTUREACCESSMODEL environment
  condition: succeeded()
  variables:
  - group: dfc-shared-pp
  - group: dfc-futureaccessmodel-shared-pp
  - template: VariableTemplates\SharedEnvironmentVariables.yml
  - template: VariableTemplates\PPEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/Deploy.yml
    parameters:
      AzureSubscription: 'SFA-DIG-PreProd (931bc9f6-359c-4f65-a753-1ee191a1fd6c)'
      Environment: PP_FUTUREACCESSMODEL
      FunctionAppName: dfc-pp-fam-la-fa
      ResourceGroup: dfc-pp-fam-la-rg
      ApimResourceGroup: '$(sharedResourceGroup)'
      ApimInstanceName: '$(ApimServiceName)'
      ApimProductId: '${{ variables.ApimProductId }}'
      ApiName: '${{ variables.ApimApiName }}'
      SwaggerSpecificationUrl: 'https://dfc-pp-fam-la-fa.$(FunctionAppDomain)${{ variables.SwaggerDefinitionPath }}'

- stage: DeployTo_PRD
  displayName: Deploy to PRD_FUTUREACCESSMODEL environment
  condition: succeeded()
  variables:
  - group: dfc-shared-prd
  - group: dfc-futureaccessmodel-shared-prd
  - template: VariableTemplates\SharedEnvironmentVariables.yml
  - template: VariableTemplates\PRDEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/Deploy.yml
    parameters:
      AzureSubscription: 'SFA-DIG-Prod (6c93f7dc-6c36-4ea6-8de3-3f4574f88027)'
      Environment: PRD_FUTUREACCESSMODEL
      FunctionAppName: dfc-prd-fam-la-fa
      ResourceGroup: dfc-prd-fam-la-rg
      ApimResourceGroup: '$(sharedResourceGroup)'
      ApimInstanceName: '$(ApimServiceName)'
      ApimProductId: '${{ variables.ApimProductId }}'
      ApiName: '${{ variables.ApimApiName }}'
      SwaggerSpecificationUrl: 'https://dfc-prd-fam-la-fa.$(FunctionAppDomain)${{ variables.SwaggerDefinitionPath }}'

