variables:
- name: ApimProductName
  value: 'Future Access Model'
- name:  ApimProductId
  value: 'future-access-model'
- name: ApimApiUrlSuffix
  value: futureaccessmodel/localauthorities
- name: ApimApiName
  value: localauthorities
- name: SwaggerDefinitionPath
  value: /api/localauthorities/api-definition